#!/bin/bash
echo Starting Jenkins build
python run.py
ecode=$?
echo AAA $ecode BBB
if [ $ecode -eq 0 ]
then
  echo all well
else
  echo run.py failed: exit code $ecode
  exit 1
fi
echo Ending Jenkins build